[nc]
txn.log.dir=/mnt/instance/data/red/txnlog 
core.dump.dir=/mnt/instance/data/red/coredump
iodevices=/mnt/instance/data/iodevice1,/mnt/instance/data/iodevice2,/mnt/instance/data/iodevice3,/mnt/instance/data/iodevice4
command=asterixnc
jvm.args= -Xmx13107m --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED

# jvm.args=  80% of the total memory of the node

[nc/1]
nc.api.port=19004
address=xxx.xx.xx.xx # replace with the IP address of the NC 1 node

[nc/2]
nc.api.port=19004
address=xxx.xx.xx.xx # replace with the IP address of the NC 2 node

[nc/3]
nc.api.port=19004
address=xxx.xx.xx.xx # replace with the IP address of the NC 3 node

[nc/4]
nc.api.port=19004
address=xxx.xx.xx.xx # replace with the IP address of the NC 4 node

[cc]
address=xxx.xx.xx.xx # replace with the IP address of the CC node can be same as NC node which should be queried argument 

[common]
log.dir = logs/
log.level = INFO
cloud.deployment=true
storage.buffercache.pagesize=128KB
storage.partitioning=static
cloud.storage.scheme=s3
cloud.storage.bucket= # name of the bucket to use for cloud storage
cloud.storage.region= #region of the bucket to use for cloud storage replace with the region of the bucket
cloud.storage.anonymous.auth=false
cloud.storage.cache.policy=selective
compiler.framesize=128KB
storage.partitions.count = 32
